[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
priority-queue = "1.3.0"
petgraph = "0.6.2"
regex = "1"
bimap = "0.6.2"